// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aivara-os/BoldGradient.tsx": () => import("../components/mockups/aivara-os/BoldGradient.tsx"),
  "./components/mockups/aivara-os/EnterpriseCalm.tsx": () => import("../components/mockups/aivara-os/EnterpriseCalm.tsx")
};
